### ISSUE TITLE
 [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)

### ISSUE THREAD

**Issue by my5123** [acheong08/EdgeGPT#188] opened 2023-03-23 10:01 UTC
E:\>python -m EdgeGPT --cookie-file "/cookie.json"

        EdgeGPT - A demo of reverse engineering the Bing GPT chatbot
        Repo: github.com/acheong08/EdgeGPT
        By: Antonio Cheong

        !help for help

        Type !exit to exit
        Enter twice to send message or set --enter-once to send one line message

Initializing...
Enter `alt+enter` or `escape+enter` to send a message
Traceback (most recent call last):
  File "D:\Python\Python38\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "D:\Python\Python38\lib\site-packages\httpcore\backends\sync.py", line 62, in start_tls
    raise exc
  File "D:\Python\Python38\lib\site-packages\httpcore\backends\sync.py", line 57, in start_tls
    sock = ssl_context.wrap_socket(
  File "D:\Python\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Python\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "D:\Python\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\Python38\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "D:\Python\Python38\lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "D:\Python\Python38\lib\site-packages\httpcore\_sync\connection_pool.py", line 253, in handle_request
    raise exc
  File "D:\Python\Python38\lib\site-packages\httpcore\_sync\connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "D:\Python\Python38\lib\site-packages\httpcore\_sync\http_proxy.py", line 261, in handle_request
    connect_response = self._connection.handle_request(
  File "D:\Python\Python38\lib\site-packages\httpcore\_sync\connection.py", line 86, in handle_request
    raise exc
  File "D:\Python\Python38\lib\site-packages\httpcore\_sync\connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "D:\Python\Python38\lib\site-packages\httpcore\_sync\connection.py", line 150, in _connect
    stream = stream.start_tls(**kwargs)
  File "D:\Python\Python38\lib\site-packages\httpcore\backends\sync.py", line 62, in start_tls
    raise exc
  File "D:\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\Python\Python38\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python\Python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python\Python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python\Python38\lib\site-packages\EdgeGPT.py", line 464, in <module>
    asyncio.run(main())
  File "D:\Python\Python38\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "D:\Python\Python38\lib\asyncio\base_events.py", line 608, in run_until_complete
    return future.result()
  File "D:\Python\Python38\lib\site-packages\EdgeGPT.py", line 377, in main
    bot = Chatbot()
  File "D:\Python\Python38\lib\site-packages\EdgeGPT.py", line 307, in __init__
    self.chat_hub: ChatHub = ChatHub(Conversation(self.cookiePath, self.cookies))
  File "D:\Python\Python38\lib\site-packages\EdgeGPT.py", line 212, in __init__
    response = self.session.get(
  File "D:\Python\Python38\lib\site-packages\httpx\_client.py", line 1045, in get
    return self.request(
  File "D:\Python\Python38\lib\site-packages\httpx\_client.py", line 821, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\Python\Python38\lib\site-packages\httpx\_client.py", line 908, in send
    response = self._send_handling_auth(
  File "D:\Python\Python38\lib\site-packages\httpx\_client.py", line 936, in _send_handling_auth
    response = self._send_handling_redirects(
  File "D:\Python\Python38\lib\site-packages\httpx\_client.py", line 973, in _send_handling_redirects
    response = self._send_single_request(request)
  File "D:\Python\Python38\lib\site-packages\httpx\_client.py", line 1009, in _send_single_request
    response = transport.handle_request(request)
  File "D:\Python\Python38\lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "D:\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\Python\Python38\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)

**Comment by acheong08** [comment] 2023-03-23 10:26
Duplicate of #188

**Closed by acheong08** 2023-03-23 10:26 UTC
