### ISSUE TITLE
[feature request] Support coauthor

### ISSUE THREAD

**Issue by Zrincet** [acheong08/EdgeGPT#90] opened 2023-03-02 01:43 UTC
In `https://edgeservices.bing.com/edgediscover/query?&lightschemeovr=1&FORM=SHORUN&udscs=1&udsnav=1&setlang=zh-CN&features=udssydinternal&clientscopes=windowheader,coauthor,chat,&udsframed=1`

Here is a module for writing articles, the API uses the same as the Chat module. Just different parameters.

**Comment by acheong08** [comment] 2023-03-02 01:44
Duplicate of #77

Might support when I have the time

**Closed by acheong08** 2023-03-02 01:44 UTC
