### ISSUE TITLE
Exception: Authentication failed

### ISSUE THREAD

**Issue by joyspce** [acheong08/EdgeGPT#183] opened 2023-03-23 08:03 UTC
when i input  python3 -m EdgeGPT --cookie-file "/mnt/disk/cookies6.json"

enter

yestoday it work perfect

get this answer:

r,n)}};sj_evt.bind("ajax.unload",c);i.send();f>0&&(e=l(function(){c();s(r,!1)},f))};var __spreadArray=this&&this.__spreadArray||function(n,t,i){if(i||arguments.length===2)for(var r=0,f=t.length,u;r<f;r++)!u&&r in t||(u||(u=Array.prototype.slice.call(t,0,r)),u[r]=t[r]);return n.concat(u||Array.prototype.slice.call(t))},BncHeadCtrl;(function(){function o(){var i=_ge("id_h"),n=_ge("id_nc");sj_be(i,"mouseover",t);sj_be(n,"focus",t);sj_be(n,"click",function(n){t();BNCenter.hdrClk=n})}function t(){sj_evt.fire("onBNCHover")}function s(){u=sb_gt();sj_ajax(h("/bnc/bellGleam"),{callback:c})}function h(n){return _w.TU?TU.acpp(n):n}function c(t,r){if(f=sb_gt(),!t||!r){n("ApiFailure",i);return}sj_evt.fire("BNCHCLoaded");l(r);a(BNCenter.unreadCountResponse);y(BNCenter.unreadCountResponse.c)}function n(t,i,r){var f,u,e;for(r===void 0&&(r=!1),f=[],u=3;u<arguments.length;u++)f[u-3]=arguments[u];if(!_w.Log||!Log.Log){sb_st(function(){return n.apply(void 0,__spreadArray([t,i,r],f,!1))},1e3);return}e=f.map(function(n){return n==null?null:n.toString()});Log.Log.apply(Log,__spreadArray([t,"BNCenter",i,r],e,!1))}function l(n){var t=sj_ce("div"),o,i,u,f,e,s;n.appendTo(t);o=[].slice.call(t.getElementsByTagName("style"));o.forEach(function(n){return _d.head.appendChild(n)});i=_qs(".bnc-hci");u=_qs(".".concat(r),t);i&&u&&i.appendChild(u);f=_ge("id_nc");e=_qs(".bnc-f",t);f&&e&&f.insertAdjacentElement("afterend",e);s=[].slice.call(t.getElementsByTagName("script"));s.forEach(function(n){return _d.body.appendChild(n)})}function a(t){var r=sb_gt()-performance.timing.loadEventEnd;n.apply(void 0,__spreadArray(["ContentStatistics",i,!1,"UNCount",t.c,"TraceId",t.tid,"WasBellIconShown",!0,"IsEligibleForBellIcon",!0,"TimeSincePageLoad",r,"Latency",f-u],v(t.sc),!1))}function v(n){var t=[];return Object.keys(n).forEach(function(i){n[i]>0&&t.push(i,n[i])}),t}function y(n){n<1||(_d.title="(".concat(n,") ").concat(_d.title),localStorage.setItem("bnc_unread_count",n.toString()),_w.addEventListener("storage",function(n){n.key==="bnc_unread_count"&&n.newValue==null&&(_d.title=_d.title.replace(/^\(\d+\) /,""),p())}))}function p(){var n=_qs(".".concat(r));n&&n.classList.add(e)}var i="NotificationCount",r="bnc-hcc",e="b_hide",u,f;_w.BNCenter=_w.BNCenter||{};BNCenter.inst=n,function(){o();s()}()})(BncHeadCtrl||(BncHeadCtrl={}));var BNCenter=BNCenter||{}; BNCenter.insertId="SERP.5060";;
//]]></script><script type="text/rms" nonce="S3Dn5Y6zcgnYQ/54K0xV3pDFPhwFpwSAaSRN10jbRNo=">//<![CDATA[
setTimeout(RedirectErrorPage.init(), 2);;
//]]></script><script type="text/rms" nonce="S3Dn5Y6zcgnYQ/54K0xV3pDFPhwFpwSAaSRN10jbRNo=">//<![CDATA[
window["fbk_1"] = function() { Feedback.Bootstrap.InitializeFeedback({page:true},"sb_feedback",1,0,0); sj_evt.unbind("fdbkbtstrp_init", window["fbk_1"]); }; sj_evt.bind("fdbkbtstrp_init", window["fbk_1"], 1);;
//]]></script></div><script type="text/javascript" nonce="S3Dn5Y6zcgnYQ/54K0xV3pDFPhwFpwSAaSRN10jbRNo=" >//<![CDATA[
_G.HT=new Date;
//]]></script></body></html>
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/EdgeGPT.py", line 467, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/EdgeGPT.py", line 378, in main
    bot = Chatbot()
  File "/usr/local/lib/python3.8/dist-packages/EdgeGPT.py", line 308, in __init__
    self.chat_hub: ChatHub = ChatHub(Conversation(self.cookiePath, self.cookies))
  File "/usr/local/lib/python3.8/dist-packages/EdgeGPT.py", line 220, in __init__
    raise Exception("Authentication failed")
Exception: Authentication failed

**Comment by Do1e** [comment] 2023-03-23 08:47
The same as #182. According to my test, this error does not occur when the real IP is overseas.

**Comment by Rayquaza-Tim** [comment] 2023-03-23 08:52
> The same as #182. According to my test, this error does not occur when the real IP is overseas.

It still happens even when I use VPN to change my IP.

**Comment by Rayquaza-Tim** [comment] 2023-03-23 10:23
> > > The same as #182. According to my test, this error does not occur when the real IP is overseas.
> > 
> > It still happens even when I use VPN to change my IP.
> 
> Maybe you should use `Global` mode. My server in Hong Kong is working well.

thanks，but this program is for those who doesn't have vpn?

**Comment by acheong08** [comment] 2023-03-23 10:25
Duplicate of #178

**Comment by acheong08** [comment] 2023-03-23 10:25
> but this program is for those who doesn't have vpn?

It will no longer work due to Microsoft's block.

**Closed by acheong08** 2023-03-23 10:25 UTC
