### ISSUE TITLE
Shared account patched

### ISSUE THREAD

**Issue by adi6409** [acheong08/EdgeGPT#21] opened 2023-02-10 16:56 UTC
Hi, i believe the shared account is now disabled.
do you have another one?
![WhatsApp Image 2023-02-10 at 18 52 25](https://user-images.githubusercontent.com/40761968/218150540-51a093bb-bf21-4022-846b-fda0feb9d8f4.jpeg)

**Comment by basetrade** [comment] 2023-02-10 17:05
Getting banned is only a matter of time

**Comment by adi6409** [comment] 2023-02-10 17:17
i know, the question is can we fix it?
maybe there is another api endpoint that doesn't require access to the BingGPT.

**Comment by Manamama** [comment] 2023-02-10 18:00
Most of such good and shiny things (kudos for the third-party account yet again) [come to pass](https://github.com/acheong08/EdgeGPT/issues/19)...

**Comment by acheong08** [comment] 2023-02-11 03:07
If anyone gets access, please contact me. We can make it accessible securely with rate limits this time.

**Comment by acheong08** [comment] 2023-02-11 11:25
Duplicate of #20

**Closed by acheong08** 2023-02-11 11:25 UTC

**Comment by Manamama** [comment] 2023-02-11 14:01
Wow, thanks. Are there (reasonable) rate limits that you have built in? (See my yesterday's modest tests and results gleaned by asking Bing ChatGPT.) 

FYI, here is what it is claiming today, bolding mine: 
> I am Bing Chat, a new feature of Bing that uses ChatGPT technology to understand questions and generate answers[^1^][7] [^2^][9]. I am not an assistant, but a search engine that can chat and create[^3^][8]. I can help you research, plan, ideate, and even create brand-new content[^4^][5]. I can also perform a variety of fun maneuvers, such as generating poems, stories, code, essays, songs, celebrity parodies and more[^5^][6]. However, there are some limitations to what I can do. For example, **I cannot perform tasks outside the chat box, such as booking a flight ticket or sending an email**. I also cannot reply with content that **violates copyrights** or is harmful to someone physically, emotionally, or financially. I also have **some rules that I cannot change or disclose, such as using # or revealing my internal alias**.
