### ISSUE TITLE
also Authentication failed @ https://edgeservices.bing.com/edgesvc/turing/conversation/create 

### ISSUE THREAD

**Issue by yuandj** [acheong08/EdgeGPT#205] opened 2023-03-24 20:11 UTC
https://edgeservices.bing.com/?form=REDIRERR

<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>0dgEeZAAAAADBI5mjkUgFSoi710uiu4lzQkoxRURHRTA5MTUARWRnZQ==

```
        EdgeGPT - A demo of reverse engineering the Bing GPT chatbot
        Repo: github.com/acheong08/EdgeGPT
        By: Antonio Cheong

        !help for help

        Type !exit to exit

Initializing...
Enter `alt+enter` or `escape+enter` to send a message
Status code: 302
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="https://cn.bing.com/edgesvc/turing/conversation/create">here</a>.</h2>
</body></html>

https://edgeservices.bing.com/edgesvc/turing/conversation/create
回溯 (最近调用显示在最后):
  文件 "C:\Users\Administrator\Desktop\2022\grasspy\lib\runpy.py", 行 192, 于 _run_module_as_main
    return _run_code(code, main_globals, None,
  文件 "C:\Users\Administrator\Desktop\2022\grasspy\lib\runpy.py", 行 85, 于 _run_code
    exec(code, run_globals)
  文件 "C:\Users\Administrator\Desktop\2022\grasspy\lib\site-packages\EdgeGPT.py", 行 489, 于 <module>
    asyncio.run(main())
  文件 "C:\Users\Administrator\Desktop\2022\grasspy\lib\asyncio\runners.py", 行 43, 于 run
    return loop.run_until_complete(main)
  文件 "C:\Users\Administrator\Desktop\2022\grasspy\lib\asyncio\base_events.py", 行 608, 于 run_until_complete
    return future.result()
  文件 "C:\Users\Administrator\Desktop\2022\grasspy\lib\site-packages\EdgeGPT.py", 行 391, 于 main
    bot = Chatbot(proxy=args.proxy)
  文件 "C:\Users\Administrator\Desktop\2022\grasspy\lib\site-packages\EdgeGPT.py", 行 320, 于 __init__
    Conversation(self.cookiePath, self.cookies, self.proxy)
  文件 "C:\Users\Administrator\Desktop\2022\grasspy\lib\site-packages\EdgeGPT.py", 行 225, 于 __init__
    raise Exception("Authentication failed")
Exception: Authentication failed
```

```
        # Send GET request
        response = self.session.get(
            url=os.environ.get("BING_PROXY_URL")
            or "https://edgeservices.bing.com/edgesvc/turing/conversation/create"
        )
        if response.status_code != 200:
            print(f"Status code: {response.status_code}")
            print(response.text)
            print(response.url)
            raise Exception("Authentication failed")
```

**Comment by VMTask** [comment] 2023-03-25 00:01
Please open [Link](https://github.com/acheong08/EdgeGPT-Proxy) to install the proxy on non-china's server,and `export BING_PROXY_URL=<SERVERIP:8080>/edgesvc/turing/conversation/create`

**Comment by acheong08** [comment] 2023-03-25 02:50
`export BING_PROXY_URL="https://edge.churchless.tech/edgesvc/turing/conversation/create"`

**Comment by acheong08** [comment] 2023-03-25 02:52
Duplicate of #178

**Closed by acheong08** 2023-03-25 02:52 UTC
