### ISSUE TITLE
cant download pictures

### ISSUE THREAD

**Issue by alphaokxyz** [acheong08/EdgeGPT#238] opened 2023-03-30 03:54 UTC
:~# python3 -m ImageGen --cookie-file /file/cookies2.json --prompt sun --output-dir /file/picture
Sending request...
Waiting for results...
.
Downloading images...

end,and folder is empty

**Comment by xudazhu1** [comment] 2023-03-30 04:42
在等待作者更新之前, 可以自己改一下ImageGen.py中的判断部分代码
如下: `
....
print("Waiting for results...")
        start_wait = time.time()
        while True:
            if int(time.time() - start_wait) > 300:
                raise Exception("Timeout error")
            print(".", end="", flush=True)
            response = self.session.get(polling_url)
            if response.status_code != 200:
                raise Exception("Could not get results")
            image_links = regex.findall(r'src="([^"]+)"', response.text)
            if image_links and len(image_links):
                break
            else:
                continue
....`

**Comment by phamxtien** [comment] 2023-03-30 15:45
@xudazhu1 Raise Error: Redirect Fail :)

**Comment by acheong08** [comment] 2023-03-31 03:22
Duplicate of #197

**Closed by acheong08** 2023-03-31 03:22 UTC
