### ISSUE TITLE
Exception: Authentication failed

### ISSUE THREAD

**Issue by Rayquaza-Tim** [acheong08/EdgeGPT#182] opened 2023-03-23 07:42 UTC
ERROR:
`
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\lib\site-packages\EdgeGPT.py", line 464, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Program Files\Python39\lib\site-packages\EdgeGPT.py", line 377, in main
    bot = Chatbot()
  File "C:\Program Files\Python39\lib\site-packages\EdgeGPT.py", line 307, in __init__
    self.chat_hub: ChatHub = ChatHub(Conversation(self.cookiePath, self.cookies))
  File "C:\Program Files\Python39\lib\site-packages\EdgeGPT.py", line 220, in __init__
    raise Exception("Authentication failed")
Exception: Authentication failed
`
It seems this url(https://edgeservices.bing.com/edgesvc/turing/conversation/create) is invalid and return "404". 

Hope this gets fixed soon

**Comment by acheong08** [comment] 2023-03-23 10:25
Duplicate of #178

**Closed by acheong08** 2023-03-23 10:25 UTC
