### ISSUE TITLE
[Help Needed]: Can any one tell me that how can I use the load_conversation() and the save_conversation() functions.

### ISSUE THREAD

**Issue by Meshwa428** [acheong08/EdgeGPT#480] opened 2023-06-03 17:52 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Can any one provide a brief explanation on how can i use it and please if possible provide an example code snipped

Thanks! in advance for help😊.

As a beginner I don't have much knowledge about how things work in complex codes. If any one is having a free time then please explain me that how does the load_conversation() and save_conversation() functions work and how can i get the chatId from the sydney's website pleasssssszzz.

**Comment by MonsterDruide1** [comment] 2023-06-04 20:43
Semi-duplicate of #456 

Also see https://github.com/acheong08/EdgeGPT/issues/456#issuecomment-1572420776

`save_conversation()`/`load_conversation()` are used to save the internal structure of the conversation to a file, to restore the conversation at a later point. They cannot be used to save the conversation to the on-site history.

Usage:
```
bot = await Chatbot.create()
bot.load_conversation("conversation.json")
# ... continue conversation
bot.save_conversation("conversation.json")
```

**Comment by liaozhangsheng** [comment] 2023-06-05 00:57
But it gives an error: 
async with aiofiles.Path.open(filename, “w”) as f: 
^^^^^^^^^^^^^ 
AttributeError: module ‘aiofiles’ has no attribute ‘Path’

Is this an error in EdgeGPT.py?

**Comment by liaozhangsheng** [comment] 2023-06-05 00:58
> 

But it gives an error: async with aiofiles.Path.open(filename, “w”) as f: ^^^^^^^^^^^^^ AttributeError: module ‘aiofiles’ has no attribute ‘Path’

Is this an error in EdgeGPT.py?

**Comment by liaozhangsheng** [comment] 2023-06-05 01:01
> Semi-duplicate of #456
> 
> Also see [#456 (comment)](https://github.com/acheong08/EdgeGPT/issues/456#issuecomment-1572420776)
> 
> `save_conversation()`/`load_conversation()` are used to save the internal structure of the conversation to a file, to restore the conversation at a later point. They cannot be used to save the conversation to the on-site history.
> 
> Usage:
> 
> ```python
> bot = await Chatbot.create()
> bot.load_conversation("conversation.json")
> # ... continue conversation
> bot.save_conversation("conversation.json")
> ```

But it gives an error: 
async with aiofiles.Path.open(filename, “w”) as f: 
^^^^^^^^^^^^^ 
AttributeError: module ‘aiofiles’ has no attribute ‘Path’

Is this an error in EdgeGPT.py?

**Comment by phamxtien** [comment] 2023-06-05 05:41
Not raise an error but bing_conversation.json has no content

```
if os.path.exists('bing_conversation.json'):  
    bot.load_conversation('bing_conversation.json')
response = await bot.ask(prompt=prompt, conversation_style=conversation_style)
bot.save_conversation('bing_conversation.json')
await bot.close()      
```
How to save conversation?

**Comment by acheong08** [comment] 2023-06-05 11:38
There are bugs. I will fix today

**Closed** 2023-06-05 14:24 UTC

**Comment by MonsterDruide1** [comment] 2023-06-06 20:45
> But it gives an error: async with aiofiles.Path.open(filename, “w”) as f: ^^^^^^^^^^^^^ AttributeError: module ‘aiofiles’ has no attribute ‘Path’

It was an issue a few days ago, but updating the module using `python3 -m pip install EdgeGPT --upgrade` should fix it.
