### ISSUE TITLE
KeyError: 'conversationSignature'

### ISSUE THREAD

**Issue by IbrahimLakhzine** [acheong08/EdgeGPT#26] opened 2023-02-11 11:24 UTC
I am running the program but when starting it gives the following error 
 Traceback (most recent call last):
  File "C:\Users\ibrahim.l\Desktop\MicroEdgeGPT.py", line 60, in <module>
    asyncio.run(main())
  File "C:\Users\ibrahim.l\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ibrahim.l\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\ibrahim.l\Desktop\MicroEdgeGPT.py", line 33, in main
    bot = Chatbot()
  File "C:\Users\ibrahim.l\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 239, in __init__        
    self.chat_hub: ChatHub = ChatHub(Conversation())
  File "C:\Users\ibrahim.l\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 154, in __init__        
    conversation_signature=conversation.struct["conversationSignature"],
KeyError: 'conversationSignature'

**Comment by acheong08** [comment] 2023-02-11 11:26
Duplicate of https://github.com/acheong08/EdgeGPT/issues/20

**Closed by acheong08** 2023-02-11 11:26 UTC
