### ISSUE TITLE
Exception: Authentication failed

### ISSUE THREAD

**Issue by yubuyuabc** [acheong08/EdgeGPT#46] opened 2023-02-15 07:27 UTC
![image](https://user-images.githubusercontent.com/58143197/218960182-56d883e7-7803-43d2-ac63-6921ec9459ca.png)

I've made a cookies.json, but still error like this picture

**Comment by acheong08** [comment] 2023-02-15 07:28
It means you don't have beta access

**Comment by yubuyuabc** [comment] 2023-02-15 07:30
In fact, I have new bing chat access

**Comment by Irisaka** [comment] 2023-02-15 07:50
The same issue, I have beta access but still get "Authentication failed".

**Comment by Manamama** [comment] 2023-02-15 08:00
A tip from the Very Large Lettered status quo: 
`UPDATE 2023/02/14 - Do not use for now while I verify its safety`

Now, how long have you waited for that beta access, guys? Any tips to expedite that before they chroot jail it further?

**Comment by acheong08** [comment] 2023-02-15 09:16
> In fact, I have new bing chat access

How did you write the cookies.json. Is the format correct? Does it include the _U cookie? What version did you run? Did you point it to the right path?

**Comment by acheong08** [comment] 2023-02-15 09:17
![image](https://user-images.githubusercontent.com/36258159/218985373-a9be3efe-8718-48ba-b53b-8e3f80fdabfb.png)

**Comment by acheong08** [comment] 2023-02-15 09:18
My `cookie.json`:
```json
[
    {
        "domain": "www.bing.com",
        "hostOnly": true,
        "httpOnly": false,
        "name": "_U",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": true,
        "storeId": null,
        "value": "..."
    }
]
```

**Comment by acheong08** [comment] 2023-02-15 09:19
> ![image](https://user-images.githubusercontent.com/58143197/218960182-56d883e7-7803-43d2-ac63-6921ec9459ca.png)
> 
> I've made a cookies.json, but still error like this picture

I see. You didn't set the environment variable

**Comment by acheong08** [comment] 2023-02-15 09:19
I'll add more documentation for developer usage

**Comment by acheong08** [comment] 2023-02-15 09:20
Set `export COOKIE_FILE=/path/to/cookies.json`

**Comment by superhermes** [comment] 2023-02-15 09:25
> My `cookie.json`:
> 
> ```json
> [
>     {
>         "domain": "www.bing.com",
>         "hostOnly": true,
>         "httpOnly": false,
>         "name": "_U",
>         "path": "/",
>         "sameSite": null,
>         "secure": false,
>         "session": true,
>         "storeId": null,
>         "value": "..."
>     }
> ]
> ```

The json that is copied with the extension in the description looks like this.

![image](https://user-images.githubusercontent.com/25399631/218987164-e9dbdeba-f19a-453e-a99f-8dcd9240ff3b.png)

**Comment by acheong08** [comment] 2023-02-15 09:26
Does `_U` show up anywhere there?

**Comment by acheong08** [comment] 2023-02-15 09:27
And the issue here is that you didn't set the cookie path as environment variable

**Comment by acheong08** [comment] 2023-02-15 09:27
> Set `export COOKIE_FILE=/path/to/cookies.json`

^ This is the solution

**Comment by Irisaka** [comment] 2023-02-15 09:49
<img width="504" alt="image" src="https://user-images.githubusercontent.com/58900145/218992415-2d55d4ae-5a5a-4211-8bc6-7c7344d704b4.png">
<img width="295" alt="image" src="https://user-images.githubusercontent.com/58900145/218992746-e9ffcf01-1648-42ee-9f5a-2a4b7e83695c.png">
Confused.

**Comment by laixiao** [comment] 2023-02-15 11:07
![I70NTU(~`_)`2ZKUD49 N5C](https://user-images.githubusercontent.com/7324402/219010929-f9eb31b1-eb40-4841-9627-43ae9898704c.png)
![TGTVEVK{W3R~UO7ZIY(6B}A](https://user-images.githubusercontent.com/7324402/219010934-4e17686d-5cb2-46e6-a3ad-15cc193cf1af.png)
![6_YT02SYM6OY_5IG46{CPRS](https://user-images.githubusercontent.com/7324402/219010940-dddbc266-a458-43b2-8525-bf6b59ae26d8.png)

**Comment by Irisaka** [comment] 2023-02-15 11:08
<img width="506" alt="image" src="https://user-images.githubusercontent.com/58900145/219011201-9b8758dc-d679-4c52-b4b2-20473fc3043d.png">
I can get cookies, but cannot pass authentication.

**Comment by acheong08** [comment] 2023-02-15 11:20
- https://github.com/acheong08/EdgeGPT/issues/48

Found the issue. You might want to check it

**Comment by acheong08** [comment] 2023-02-15 11:22
Closing and moving over to the other issue

**Comment by acheong08** [comment] 2023-02-15 11:27
ReOpening

**Comment by acheong08** [comment] 2023-02-15 11:28
We got new info that people with the KievRPSSecAuth cookie cannot use the program for some reason.

**Comment by Irisaka** [comment] 2023-02-15 11:37
<img width="757" alt="屏幕截图_20230215_193024" src="https://user-images.githubusercontent.com/58900145/219016608-65bf3c1c-a92f-42aa-bb5f-a1fc2798621b.png">
<img width="268" alt="image" src="https://user-images.githubusercontent.com/58900145/219016061-264a1568-d72c-4731-9a08-97ae9ce20d80.png">
I get the KievRPSSecAuth cookie, maybe this is the problem. In depression...

**Comment by acheong08** [comment] 2023-02-15 11:49
Oh wait there was bug in release

**Comment by acheong08** [comment] 2023-02-15 11:49
Try https://github.com/acheong08/EdgeGPT/releases/tag/0.0.42

**Comment by acheong08** [comment] 2023-02-15 11:49
And send the error logs

**Comment by Irisaka** [comment] 2023-02-15 12:00
<img width="593" alt="image" src="https://user-images.githubusercontent.com/58900145/219021655-d35afed0-0afe-45f8-8ca4-c230e5d1c044.png">
After updated, back to the original problem.

**Comment by acheong08** [comment] 2023-02-15 12:01
Can you show the bit before that?

**Comment by acheong08** [comment] 2023-02-15 12:01
It shows the error code and response text

**Comment by Irisaka** [comment] 2023-02-15 12:04
<img width="754" alt="image" src="https://user-images.githubusercontent.com/58900145/219022478-d8ec111f-7063-41d4-9942-f5b1017a8158.png">
Oh, sorry, I'm not queit familiar to this.

**Comment by acheong08** [comment] 2023-02-15 12:05
Thanks I will look into this

**Comment by 906596696** [comment] 2023-02-15 13:54
> 

This may be caused by a banned region, such as China. This can be solved by adding this to the header。Or use proxy.
"x-forwarded-for": "8.8.8.8"

**Comment by 906596696** [comment] 2023-02-15 13:54
> Thanks I will look into this

This may be caused by a banned region, such as China. This can be solved by adding this to the header。Or use proxy.
"x-forwarded-for": "8.8.8.8" @acheong08

**Comment by EightEggs** [comment] 2023-02-15 14:01
> > Thanks I will look into this
> 
> This may be caused by a banned region, such as China. This can be solved by adding this to the header。Or use proxy. "x-forwarded-for": "8.8.8.8" @acheong08

Exactly. People can use extensions in browser such as ModHeader to set `"x-forwarded-for": "8.8.8.8"`.
However we do not know how to set it in a python script.

**Comment by acheong08** [comment] 2023-02-15 16:48
> > Thanks I will look into this
> 
> This may be caused by a banned region, such as China. This can be solved by adding this to the header。Or use proxy. "x-forwarded-for": "8.8.8.8" @acheong08

Will do. Thanks for the fix

**Closed** 2023-02-15 16:50 UTC
