### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

### ISSUE THREAD

**Issue by codingwatching** [acheong08/EdgeGPT#11] opened 2023-02-10 10:49 UTC
```
python3 -m EdgeGPT

        EdgeGPT - A demo of reverse engineering the Bing GPT chatbot
        Repo: github.com/acheong08/EdgeGPT
        By: Antonio Cheong

        !help for help

        Type !exit to exit
        Enter twice to send message
    
Initializing...

You:
Hi

Bot:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/EdgeGPT.py", line 351, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/EdgeGPT.py", line 317, in main
    (await bot.ask(prompt=prompt))["item"]["messages"][1]["adaptiveCards"][0][
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/EdgeGPT.py", line 245, in ask
    return await self.chat_hub.ask(prompt=prompt)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/EdgeGPT.py", line 171, in ask
    self.wss = await websockets.connect("wss://sydney.bing.com/sydney/ChatHub")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/websockets/legacy/client.py", line 663, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1119, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
```

**Comment by acheong08** [comment] 2023-02-10 10:50
Looks like the site is blocked. Use a VPN

**Comment by codingwatching** [comment] 2023-02-10 10:54
I run ExpressVPN but still error
<img width="406" alt="image" src="https://user-images.githubusercontent.com/85933804/218074763-237f1425-784a-4032-b6e7-2b8f1c9d738a.png">

**Comment by acheong08** [comment] 2023-02-10 10:56
Network issue out of scope. I can't really fix this since it's not a problem with my code

**Comment by codingwatching** [comment] 2023-02-10 10:58
I fix this
https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate
```
For anyone who still wonders on how to fix this, i got mine by installing the "Install Certificates.command"
```

Thank you so much!

**Comment by acheong08** [comment] 2023-02-10 10:58
Duplicate of 
- #8

**Comment by acheong08** [comment] 2023-02-10 10:58
> I fix this https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate
> 
> ```
> For anyone who still wonders on how to fix this, i got mine by installing the "Install Certificates.command"
> ```

Ah nice

**Closed by acheong08** 2023-02-10 10:58 UTC

**Comment by HuaianWu** [comment] 2023-03-04 07:42
> 

this fix my problem.thanx
