### ISSUE TITLE
q = Query cookie_file不能正常运行

### ISSUE THREAD

**Issue by xhzth70911** [acheong08/EdgeGPT#453] opened 2023-05-29 11:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits
- 
在Chatbot.create可以正常运行cookie.txt
cookies = json.loads(open(os.path.abspath(f"{BASE_DIR}\cookie.txt"), encoding="utf-8").read())
bot = await Chatbot.create(cookies=cookies)

### What happened?

README_zh-cn.md里的cookies="./bing_cookies_alternative.json"在EdgeGPT.py里是cookie_file
```python
from EdgeGPT import Query, Cookie

q = Query("你是誰？用python代码給出回答")
print(q)
```

或者更改要使用的對話風格或 Cookie 檔：

```python
q = Query(
  "你是誰？用python代码給出回答",
  style="creative",  # 或者平衡模式 'balanced'
  cookies="./bing_cookies_alternative.json"
)
```

实际cookie_file
class Query:
    """
    A convenience class that wraps around EdgeGPT.Chatbot to encapsulate input,
    config, and output all together.  Relies on Cookie class for authentication
    """

    def __init__(
        self,
        prompt,
        style="precise",
        content_type="text",
        cookie_file=0,
        echo=True,
        echo_prompt=False,
        proxy: str | None = None,
    ):

### Steps to reproduce the problem

import os
from EdgeGPT import Query, Cookie

BASE_DIR = os.getcwd()
if __name__ == "__main__":
    print(BASE_DIR+"\cookie.txt")
    q = Query(
        prompt="长城公司举报比亚迪是什么事",
        style="creative",  # 或者平衡模式 'balanced'
        cookie_file=BASE_DIR+"\cookie.txt"
    )
    print(q)

终端输出:
C:\Program Files\JetBrains\PyCharm 2020.3.1\plugins\python\helpers\pydev\pydevd.py:1838: DeprecationWarning: currentThread() is deprecated, use current_thread() instead
  dummy_thread = threading.currentThread()
Connected to pydev debugger (build 203.6682.86)
D:\code\python\new\EdgeGPT-0.6.9\cookie.txt
> Please set Cookie.current_filepath to a valid cookie file, then run Cookie.import_data()
python-BaseException
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2020.3.1\plugins\python\helpers\pydev\pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.3.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/code/python/new/EdgeGPT-0.6.9/src/testGPT.py", line 26, in <module>
    q = Query(
  File "D:\code\python\new\EdgeGPT-0.6.9\src\EdgeGPT.py", line 1052, in __init__
    self.log_and_send_query(echo, echo_prompt)
  File "D:\code\python\new\EdgeGPT-0.6.9\src\EdgeGPT.py", line 1058, in log_and_send_query
    name = str(Cookie.current_filepath.name)
AttributeError: type object 'Cookie' has no attribute 'current_filepath'. Did you mean: 'current_file_index'?

### What should have happened?

cookie_file正常执行

### Version where the problem happens

EdgeGPT:0.6.9

### What Python version are you running this with?

Python 3.10.9

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
否
```

### Console logs

```Shell
C:\Program Files\JetBrains\PyCharm 2020.3.1\plugins\python\helpers\pydev\pydevd.py:1838: DeprecationWarning: currentThread() is deprecated, use current_thread() instead
  dummy_thread = threading.currentThread()
Connected to pydev debugger (build 203.6682.86)
D:\code\python\new\EdgeGPT-0.6.9\cookie.txt
> Please set Cookie.current_filepath to a valid cookie file, then run Cookie.import_data()
python-BaseException
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2020.3.1\plugins\python\helpers\pydev\pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.3.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/code/python/new/EdgeGPT-0.6.9/src/testGPT.py", line 26, in <module>
    q = Query(
  File "D:\code\python\new\EdgeGPT-0.6.9\src\EdgeGPT.py", line 1052, in __init__
    self.log_and_send_query(echo, echo_prompt)
  File "D:\code\python\new\EdgeGPT-0.6.9\src\EdgeGPT.py", line 1058, in log_and_send_query
    name = str(Cookie.current_filepath.name)
AttributeError: type object 'Cookie' has no attribute 'current_filepath'. Did you mean: 'current_file_index'?
```

**Comment by acheong08** [comment] 2023-05-29 12:26
Duplicate of #452

**Closed by acheong08** 2023-05-29 12:26 UTC
